name: Windows C++ Build and Release

on:
  push:
    branches:
      - '**'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build project
      run: |
        msbuild CPPSamples.sln /p:Configuration=Release /p:Platform=x64 /p:LanguageStandard=stdcpp17
      
    - name: Find built exe files
      id: exes
      run: echo "files=$(Get-ChildItem -Path . -Recurse -Filter *.exe | Select-Object -ExpandProperty FullName -join ',')" >> $env:GITHUB_OUTPUT

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload exe files to Release
      uses: actions/upload-release-asset@v1
      if: steps.exes.outputs.files != ''
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ matrix.file }}
        asset_name: ${{ matrix.file }}
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        file: ${{ fromJson(format('[{0}]', steps.exes.outputs.files)) }}
