name: Windows C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v2

    - name: Build the solution
      run: msbuild CPPSamples.sln /p:Configuration=Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cpp-executables
        path: |
          **/Release/*.exe
          **/Release/*.dll
          **/Release/*.pdb